//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TemperatureSensorDataEntities : DbContext
    {
        public TemperatureSensorDataEntities()
            : base("name=TemperatureSensorDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Sensor> Sensors { get; set; }
        public DbSet<SensorArray> SensorArrays { get; set; }
        public DbSet<TempratureReading> TempratureReadings { get; set; }
    }
}
