//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensor
    {
        public Sensor()
        {
            this.TempratureReadings = new HashSet<TempratureReading>();
        }
    
        public int SensorID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> SensorArrayID { get; set; }
        public string Description { get; set; }
    
        public virtual SensorArray SensorArray { get; set; }
        public virtual ICollection<TempratureReading> TempratureReadings { get; set; }
    }
}
