//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempratureMonitor.HCMIS.Sensors {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://SenserService.hcmis.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SenserService.hcmis.org/", ConfigurationName="HCMIS.Sensors.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name GetLatestTempratureReadingFromDBResult from namespace http://SenserService.hcmis.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SenserService.hcmis.org/GetLatestTempratureReadingFromDB", ReplyAction="*")]
        TempratureMonitor.HCMIS.Sensors.GetLatestTempratureReadingFromDBResponse GetLatestTempratureReadingFromDB(TempratureMonitor.HCMIS.Sensors.GetLatestTempratureReadingFromDBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SenserService.hcmis.org/GetLatestTempratureReadingFromDB", ReplyAction="*")]
        System.Threading.Tasks.Task<TempratureMonitor.HCMIS.Sensors.GetLatestTempratureReadingFromDBResponse> GetLatestTempratureReadingFromDBAsync(TempratureMonitor.HCMIS.Sensors.GetLatestTempratureReadingFromDBRequest request);
        
        // CODEGEN: Generating message contract since element name GetLiveTempratureReadingResult from namespace http://SenserService.hcmis.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://SenserService.hcmis.org/GetLiveTempratureReading", ReplyAction="*")]
        TempratureMonitor.HCMIS.Sensors.GetLiveTempratureReadingResponse GetLiveTempratureReading(TempratureMonitor.HCMIS.Sensors.GetLiveTempratureReadingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SenserService.hcmis.org/GetLiveTempratureReading", ReplyAction="*")]
        System.Threading.Tasks.Task<TempratureMonitor.HCMIS.Sensors.GetLiveTempratureReadingResponse> GetLiveTempratureReadingAsync(TempratureMonitor.HCMIS.Sensors.GetLiveTempratureReadingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLatestTempratureReadingFromDBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLatestTempratureReadingFromDB", Namespace="http://SenserService.hcmis.org/", Order=0)]
        public TempratureMonitor.HCMIS.Sensors.GetLatestTempratureReadingFromDBRequestBody Body;
        
        public GetLatestTempratureReadingFromDBRequest() {
        }
        
        public GetLatestTempratureReadingFromDBRequest(TempratureMonitor.HCMIS.Sensors.GetLatestTempratureReadingFromDBRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetLatestTempratureReadingFromDBRequestBody {
        
        public GetLatestTempratureReadingFromDBRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLatestTempratureReadingFromDBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLatestTempratureReadingFromDBResponse", Namespace="http://SenserService.hcmis.org/", Order=0)]
        public TempratureMonitor.HCMIS.Sensors.GetLatestTempratureReadingFromDBResponseBody Body;
        
        public GetLatestTempratureReadingFromDBResponse() {
        }
        
        public GetLatestTempratureReadingFromDBResponse(TempratureMonitor.HCMIS.Sensors.GetLatestTempratureReadingFromDBResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SenserService.hcmis.org/")]
    public partial class GetLatestTempratureReadingFromDBResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TempratureMonitor.HCMIS.Sensors.ArrayOfString GetLatestTempratureReadingFromDBResult;
        
        public GetLatestTempratureReadingFromDBResponseBody() {
        }
        
        public GetLatestTempratureReadingFromDBResponseBody(TempratureMonitor.HCMIS.Sensors.ArrayOfString GetLatestTempratureReadingFromDBResult) {
            this.GetLatestTempratureReadingFromDBResult = GetLatestTempratureReadingFromDBResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLiveTempratureReadingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLiveTempratureReading", Namespace="http://SenserService.hcmis.org/", Order=0)]
        public TempratureMonitor.HCMIS.Sensors.GetLiveTempratureReadingRequestBody Body;
        
        public GetLiveTempratureReadingRequest() {
        }
        
        public GetLiveTempratureReadingRequest(TempratureMonitor.HCMIS.Sensors.GetLiveTempratureReadingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetLiveTempratureReadingRequestBody {
        
        public GetLiveTempratureReadingRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLiveTempratureReadingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLiveTempratureReadingResponse", Namespace="http://SenserService.hcmis.org/", Order=0)]
        public TempratureMonitor.HCMIS.Sensors.GetLiveTempratureReadingResponseBody Body;
        
        public GetLiveTempratureReadingResponse() {
        }
        
        public GetLiveTempratureReadingResponse(TempratureMonitor.HCMIS.Sensors.GetLiveTempratureReadingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://SenserService.hcmis.org/")]
    public partial class GetLiveTempratureReadingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLiveTempratureReadingResult;
        
        public GetLiveTempratureReadingResponseBody() {
        }
        
        public GetLiveTempratureReadingResponseBody(string GetLiveTempratureReadingResult) {
            this.GetLiveTempratureReadingResult = GetLiveTempratureReadingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : TempratureMonitor.HCMIS.Sensors.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<TempratureMonitor.HCMIS.Sensors.Service1Soap>, TempratureMonitor.HCMIS.Sensors.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TempratureMonitor.HCMIS.Sensors.GetLatestTempratureReadingFromDBResponse TempratureMonitor.HCMIS.Sensors.Service1Soap.GetLatestTempratureReadingFromDB(TempratureMonitor.HCMIS.Sensors.GetLatestTempratureReadingFromDBRequest request) {
            return base.Channel.GetLatestTempratureReadingFromDB(request);
        }
        
        public TempratureMonitor.HCMIS.Sensors.ArrayOfString GetLatestTempratureReadingFromDB() {
            TempratureMonitor.HCMIS.Sensors.GetLatestTempratureReadingFromDBRequest inValue = new TempratureMonitor.HCMIS.Sensors.GetLatestTempratureReadingFromDBRequest();
            inValue.Body = new TempratureMonitor.HCMIS.Sensors.GetLatestTempratureReadingFromDBRequestBody();
            TempratureMonitor.HCMIS.Sensors.GetLatestTempratureReadingFromDBResponse retVal = ((TempratureMonitor.HCMIS.Sensors.Service1Soap)(this)).GetLatestTempratureReadingFromDB(inValue);
            return retVal.Body.GetLatestTempratureReadingFromDBResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TempratureMonitor.HCMIS.Sensors.GetLatestTempratureReadingFromDBResponse> TempratureMonitor.HCMIS.Sensors.Service1Soap.GetLatestTempratureReadingFromDBAsync(TempratureMonitor.HCMIS.Sensors.GetLatestTempratureReadingFromDBRequest request) {
            return base.Channel.GetLatestTempratureReadingFromDBAsync(request);
        }
        
        public System.Threading.Tasks.Task<TempratureMonitor.HCMIS.Sensors.GetLatestTempratureReadingFromDBResponse> GetLatestTempratureReadingFromDBAsync() {
            TempratureMonitor.HCMIS.Sensors.GetLatestTempratureReadingFromDBRequest inValue = new TempratureMonitor.HCMIS.Sensors.GetLatestTempratureReadingFromDBRequest();
            inValue.Body = new TempratureMonitor.HCMIS.Sensors.GetLatestTempratureReadingFromDBRequestBody();
            return ((TempratureMonitor.HCMIS.Sensors.Service1Soap)(this)).GetLatestTempratureReadingFromDBAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TempratureMonitor.HCMIS.Sensors.GetLiveTempratureReadingResponse TempratureMonitor.HCMIS.Sensors.Service1Soap.GetLiveTempratureReading(TempratureMonitor.HCMIS.Sensors.GetLiveTempratureReadingRequest request) {
            return base.Channel.GetLiveTempratureReading(request);
        }
        
        public string GetLiveTempratureReading() {
            TempratureMonitor.HCMIS.Sensors.GetLiveTempratureReadingRequest inValue = new TempratureMonitor.HCMIS.Sensors.GetLiveTempratureReadingRequest();
            inValue.Body = new TempratureMonitor.HCMIS.Sensors.GetLiveTempratureReadingRequestBody();
            TempratureMonitor.HCMIS.Sensors.GetLiveTempratureReadingResponse retVal = ((TempratureMonitor.HCMIS.Sensors.Service1Soap)(this)).GetLiveTempratureReading(inValue);
            return retVal.Body.GetLiveTempratureReadingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TempratureMonitor.HCMIS.Sensors.GetLiveTempratureReadingResponse> TempratureMonitor.HCMIS.Sensors.Service1Soap.GetLiveTempratureReadingAsync(TempratureMonitor.HCMIS.Sensors.GetLiveTempratureReadingRequest request) {
            return base.Channel.GetLiveTempratureReadingAsync(request);
        }
        
        public System.Threading.Tasks.Task<TempratureMonitor.HCMIS.Sensors.GetLiveTempratureReadingResponse> GetLiveTempratureReadingAsync() {
            TempratureMonitor.HCMIS.Sensors.GetLiveTempratureReadingRequest inValue = new TempratureMonitor.HCMIS.Sensors.GetLiveTempratureReadingRequest();
            inValue.Body = new TempratureMonitor.HCMIS.Sensors.GetLiveTempratureReadingRequestBody();
            return ((TempratureMonitor.HCMIS.Sensors.Service1Soap)(this)).GetLiveTempratureReadingAsync(inValue);
        }
    }
}
